// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/plaidfinances/plaidFinances.proto

package plaidfinances

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type LinkFinancialInstitutionRequest struct {
	PublicToken          string   `protobuf:"bytes,1,opt,name=public_token,json=publicToken,proto3" json:"public_token,omitempty"`
	PlaidInstitutionId   string   `protobuf:"bytes,2,opt,name=plaid_institution_id,json=plaidInstitutionId,proto3" json:"plaid_institution_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkFinancialInstitutionRequest) Reset()         { *m = LinkFinancialInstitutionRequest{} }
func (m *LinkFinancialInstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*LinkFinancialInstitutionRequest) ProtoMessage()    {}
func (*LinkFinancialInstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{1}
}

func (m *LinkFinancialInstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkFinancialInstitutionRequest.Unmarshal(m, b)
}
func (m *LinkFinancialInstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkFinancialInstitutionRequest.Marshal(b, m, deterministic)
}
func (m *LinkFinancialInstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkFinancialInstitutionRequest.Merge(m, src)
}
func (m *LinkFinancialInstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_LinkFinancialInstitutionRequest.Size(m)
}
func (m *LinkFinancialInstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkFinancialInstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkFinancialInstitutionRequest proto.InternalMessageInfo

func (m *LinkFinancialInstitutionRequest) GetPublicToken() string {
	if m != nil {
		return m.PublicToken
	}
	return ""
}

func (m *LinkFinancialInstitutionRequest) GetPlaidInstitutionId() string {
	if m != nil {
		return m.PlaidInstitutionId
	}
	return ""
}

type LinkFinancialInstitutionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkFinancialInstitutionResponse) Reset()         { *m = LinkFinancialInstitutionResponse{} }
func (m *LinkFinancialInstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*LinkFinancialInstitutionResponse) ProtoMessage()    {}
func (*LinkFinancialInstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{2}
}

func (m *LinkFinancialInstitutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkFinancialInstitutionResponse.Unmarshal(m, b)
}
func (m *LinkFinancialInstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkFinancialInstitutionResponse.Marshal(b, m, deterministic)
}
func (m *LinkFinancialInstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkFinancialInstitutionResponse.Merge(m, src)
}
func (m *LinkFinancialInstitutionResponse) XXX_Size() int {
	return xxx_messageInfo_LinkFinancialInstitutionResponse.Size(m)
}
func (m *LinkFinancialInstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkFinancialInstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkFinancialInstitutionResponse proto.InternalMessageInfo

func (m *LinkFinancialInstitutionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateFinancialInstitutionRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFinancialInstitutionRequest) Reset()         { *m = UpdateFinancialInstitutionRequest{} }
func (m *UpdateFinancialInstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFinancialInstitutionRequest) ProtoMessage()    {}
func (*UpdateFinancialInstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{3}
}

func (m *UpdateFinancialInstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFinancialInstitutionRequest.Unmarshal(m, b)
}
func (m *UpdateFinancialInstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFinancialInstitutionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFinancialInstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFinancialInstitutionRequest.Merge(m, src)
}
func (m *UpdateFinancialInstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFinancialInstitutionRequest.Size(m)
}
func (m *UpdateFinancialInstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFinancialInstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFinancialInstitutionRequest proto.InternalMessageInfo

func (m *UpdateFinancialInstitutionRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type UpdateFinancialInstitutionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFinancialInstitutionResponse) Reset()         { *m = UpdateFinancialInstitutionResponse{} }
func (m *UpdateFinancialInstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFinancialInstitutionResponse) ProtoMessage()    {}
func (*UpdateFinancialInstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{4}
}

func (m *UpdateFinancialInstitutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFinancialInstitutionResponse.Unmarshal(m, b)
}
func (m *UpdateFinancialInstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFinancialInstitutionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFinancialInstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFinancialInstitutionResponse.Merge(m, src)
}
func (m *UpdateFinancialInstitutionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFinancialInstitutionResponse.Size(m)
}
func (m *UpdateFinancialInstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFinancialInstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFinancialInstitutionResponse proto.InternalMessageInfo

func (m *UpdateFinancialInstitutionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateFinancialAccountsRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFinancialAccountsRequest) Reset()         { *m = UpdateFinancialAccountsRequest{} }
func (m *UpdateFinancialAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFinancialAccountsRequest) ProtoMessage()    {}
func (*UpdateFinancialAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{5}
}

func (m *UpdateFinancialAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFinancialAccountsRequest.Unmarshal(m, b)
}
func (m *UpdateFinancialAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFinancialAccountsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFinancialAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFinancialAccountsRequest.Merge(m, src)
}
func (m *UpdateFinancialAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFinancialAccountsRequest.Size(m)
}
func (m *UpdateFinancialAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFinancialAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFinancialAccountsRequest proto.InternalMessageInfo

func (m *UpdateFinancialAccountsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type UpdateFinancialAccountsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFinancialAccountsResponse) Reset()         { *m = UpdateFinancialAccountsResponse{} }
func (m *UpdateFinancialAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFinancialAccountsResponse) ProtoMessage()    {}
func (*UpdateFinancialAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{6}
}

func (m *UpdateFinancialAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFinancialAccountsResponse.Unmarshal(m, b)
}
func (m *UpdateFinancialAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFinancialAccountsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFinancialAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFinancialAccountsResponse.Merge(m, src)
}
func (m *UpdateFinancialAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFinancialAccountsResponse.Size(m)
}
func (m *UpdateFinancialAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFinancialAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFinancialAccountsResponse proto.InternalMessageInfo

func (m *UpdateFinancialAccountsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveFinancialInstitutionRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFinancialInstitutionRequest) Reset()         { *m = RemoveFinancialInstitutionRequest{} }
func (m *RemoveFinancialInstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFinancialInstitutionRequest) ProtoMessage()    {}
func (*RemoveFinancialInstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{7}
}

func (m *RemoveFinancialInstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFinancialInstitutionRequest.Unmarshal(m, b)
}
func (m *RemoveFinancialInstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFinancialInstitutionRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFinancialInstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFinancialInstitutionRequest.Merge(m, src)
}
func (m *RemoveFinancialInstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFinancialInstitutionRequest.Size(m)
}
func (m *RemoveFinancialInstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFinancialInstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFinancialInstitutionRequest proto.InternalMessageInfo

func (m *RemoveFinancialInstitutionRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type RemoveFinancialInstitutionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFinancialInstitutionResponse) Reset()         { *m = RemoveFinancialInstitutionResponse{} }
func (m *RemoveFinancialInstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFinancialInstitutionResponse) ProtoMessage()    {}
func (*RemoveFinancialInstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{8}
}

func (m *RemoveFinancialInstitutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFinancialInstitutionResponse.Unmarshal(m, b)
}
func (m *RemoveFinancialInstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFinancialInstitutionResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFinancialInstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFinancialInstitutionResponse.Merge(m, src)
}
func (m *RemoveFinancialInstitutionResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFinancialInstitutionResponse.Size(m)
}
func (m *RemoveFinancialInstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFinancialInstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFinancialInstitutionResponse proto.InternalMessageInfo

func (m *RemoveFinancialInstitutionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddHistoricalFinancialTransactionsRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PlaidItemId          string   `protobuf:"bytes,2,opt,name=plaid_item_id,json=plaidItemId,proto3" json:"plaid_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHistoricalFinancialTransactionsRequest) Reset() {
	*m = AddHistoricalFinancialTransactionsRequest{}
}
func (m *AddHistoricalFinancialTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*AddHistoricalFinancialTransactionsRequest) ProtoMessage()    {}
func (*AddHistoricalFinancialTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{9}
}

func (m *AddHistoricalFinancialTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsRequest.Unmarshal(m, b)
}
func (m *AddHistoricalFinancialTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *AddHistoricalFinancialTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHistoricalFinancialTransactionsRequest.Merge(m, src)
}
func (m *AddHistoricalFinancialTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsRequest.Size(m)
}
func (m *AddHistoricalFinancialTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHistoricalFinancialTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddHistoricalFinancialTransactionsRequest proto.InternalMessageInfo

func (m *AddHistoricalFinancialTransactionsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AddHistoricalFinancialTransactionsRequest) GetPlaidItemId() string {
	if m != nil {
		return m.PlaidItemId
	}
	return ""
}

type AddHistoricalFinancialTransactionsResponse struct {
	NewTransactions      int64    `protobuf:"varint,1,opt,name=newTransactions,proto3" json:"newTransactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddHistoricalFinancialTransactionsResponse) Reset() {
	*m = AddHistoricalFinancialTransactionsResponse{}
}
func (m *AddHistoricalFinancialTransactionsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*AddHistoricalFinancialTransactionsResponse) ProtoMessage() {}
func (*AddHistoricalFinancialTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{10}
}

func (m *AddHistoricalFinancialTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsResponse.Unmarshal(m, b)
}
func (m *AddHistoricalFinancialTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *AddHistoricalFinancialTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHistoricalFinancialTransactionsResponse.Merge(m, src)
}
func (m *AddHistoricalFinancialTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_AddHistoricalFinancialTransactionsResponse.Size(m)
}
func (m *AddHistoricalFinancialTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHistoricalFinancialTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddHistoricalFinancialTransactionsResponse proto.InternalMessageInfo

func (m *AddHistoricalFinancialTransactionsResponse) GetNewTransactions() int64 {
	if m != nil {
		return m.NewTransactions
	}
	return 0
}

type AddFinancialTransactionsRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PlaidItemId          string   `protobuf:"bytes,2,opt,name=plaid_item_id,json=plaidItemId,proto3" json:"plaid_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFinancialTransactionsRequest) Reset()         { *m = AddFinancialTransactionsRequest{} }
func (m *AddFinancialTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*AddFinancialTransactionsRequest) ProtoMessage()    {}
func (*AddFinancialTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{11}
}

func (m *AddFinancialTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFinancialTransactionsRequest.Unmarshal(m, b)
}
func (m *AddFinancialTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFinancialTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *AddFinancialTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFinancialTransactionsRequest.Merge(m, src)
}
func (m *AddFinancialTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_AddFinancialTransactionsRequest.Size(m)
}
func (m *AddFinancialTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFinancialTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFinancialTransactionsRequest proto.InternalMessageInfo

func (m *AddFinancialTransactionsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AddFinancialTransactionsRequest) GetPlaidItemId() string {
	if m != nil {
		return m.PlaidItemId
	}
	return ""
}

type AddFinancialTransactionsResponse struct {
	NewTransactions      int64    `protobuf:"varint,1,opt,name=newTransactions,proto3" json:"newTransactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFinancialTransactionsResponse) Reset()         { *m = AddFinancialTransactionsResponse{} }
func (m *AddFinancialTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*AddFinancialTransactionsResponse) ProtoMessage()    {}
func (*AddFinancialTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{12}
}

func (m *AddFinancialTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFinancialTransactionsResponse.Unmarshal(m, b)
}
func (m *AddFinancialTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFinancialTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *AddFinancialTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFinancialTransactionsResponse.Merge(m, src)
}
func (m *AddFinancialTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_AddFinancialTransactionsResponse.Size(m)
}
func (m *AddFinancialTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFinancialTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFinancialTransactionsResponse proto.InternalMessageInfo

func (m *AddFinancialTransactionsResponse) GetNewTransactions() int64 {
	if m != nil {
		return m.NewTransactions
	}
	return 0
}

type RemoveFinancialTransactionsRequest struct {
	TransactionIds       []int64  `protobuf:"varint,1,rep,packed,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	PlaidTransactionIds  []string `protobuf:"bytes,2,rep,name=plaid_transaction_ids,json=plaidTransactionIds,proto3" json:"plaid_transaction_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFinancialTransactionsRequest) Reset()         { *m = RemoveFinancialTransactionsRequest{} }
func (m *RemoveFinancialTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFinancialTransactionsRequest) ProtoMessage()    {}
func (*RemoveFinancialTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{13}
}

func (m *RemoveFinancialTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFinancialTransactionsRequest.Unmarshal(m, b)
}
func (m *RemoveFinancialTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFinancialTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFinancialTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFinancialTransactionsRequest.Merge(m, src)
}
func (m *RemoveFinancialTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFinancialTransactionsRequest.Size(m)
}
func (m *RemoveFinancialTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFinancialTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFinancialTransactionsRequest proto.InternalMessageInfo

func (m *RemoveFinancialTransactionsRequest) GetTransactionIds() []int64 {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

func (m *RemoveFinancialTransactionsRequest) GetPlaidTransactionIds() []string {
	if m != nil {
		return m.PlaidTransactionIds
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_55420273247af5e9, []int{14}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Category)(nil), "plaidfinances.Category")
	proto.RegisterType((*LinkFinancialInstitutionRequest)(nil), "plaidfinances.LinkFinancialInstitutionRequest")
	proto.RegisterType((*LinkFinancialInstitutionResponse)(nil), "plaidfinances.LinkFinancialInstitutionResponse")
	proto.RegisterType((*UpdateFinancialInstitutionRequest)(nil), "plaidfinances.UpdateFinancialInstitutionRequest")
	proto.RegisterType((*UpdateFinancialInstitutionResponse)(nil), "plaidfinances.UpdateFinancialInstitutionResponse")
	proto.RegisterType((*UpdateFinancialAccountsRequest)(nil), "plaidfinances.UpdateFinancialAccountsRequest")
	proto.RegisterType((*UpdateFinancialAccountsResponse)(nil), "plaidfinances.UpdateFinancialAccountsResponse")
	proto.RegisterType((*RemoveFinancialInstitutionRequest)(nil), "plaidfinances.RemoveFinancialInstitutionRequest")
	proto.RegisterType((*RemoveFinancialInstitutionResponse)(nil), "plaidfinances.RemoveFinancialInstitutionResponse")
	proto.RegisterType((*AddHistoricalFinancialTransactionsRequest)(nil), "plaidfinances.AddHistoricalFinancialTransactionsRequest")
	proto.RegisterType((*AddHistoricalFinancialTransactionsResponse)(nil), "plaidfinances.AddHistoricalFinancialTransactionsResponse")
	proto.RegisterType((*AddFinancialTransactionsRequest)(nil), "plaidfinances.AddFinancialTransactionsRequest")
	proto.RegisterType((*AddFinancialTransactionsResponse)(nil), "plaidfinances.AddFinancialTransactionsResponse")
	proto.RegisterType((*RemoveFinancialTransactionsRequest)(nil), "plaidfinances.RemoveFinancialTransactionsRequest")
	proto.RegisterType((*Empty)(nil), "plaidfinances.Empty")
}

func init() {
	proto.RegisterFile("services/plaidfinances/plaidFinances.proto", fileDescriptor_55420273247af5e9)
}

var fileDescriptor_55420273247af5e9 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0xc5, 0xf0, 0x4b, 0x48, 0xe6, 0xd7, 0x24, 0xd2, 0x96, 0x2a, 0x16, 0x95, 0x1a, 0xb2, 0x97,
	0xd2, 0x48, 0x98, 0x34, 0xbd, 0x34, 0x6a, 0x54, 0x89, 0xfe, 0x47, 0xca, 0xa1, 0x72, 0x69, 0x0f,
	0x3d, 0x14, 0x2d, 0xde, 0x2d, 0xac, 0x62, 0x76, 0x5d, 0xef, 0x9a, 0x88, 0x4a, 0x39, 0x54, 0xfd,
	0x18, 0xbd, 0xf6, 0x83, 0x56, 0xd8, 0x2e, 0x01, 0x83, 0x59, 0x12, 0xa9, 0x37, 0x66, 0x76, 0x67,
	0xde, 0xf3, 0x30, 0xef, 0x69, 0xe1, 0x48, 0xb1, 0x70, 0xc4, 0x3d, 0xa6, 0x9a, 0x81, 0x4f, 0x38,
	0xfd, 0xca, 0x05, 0x11, 0xd3, 0xe8, 0x4d, 0x1a, 0x39, 0x41, 0x28, 0xb5, 0x44, 0x3b, 0x73, 0x57,
	0xf0, 0x2b, 0xd8, 0x7a, 0x49, 0x34, 0xeb, 0xcb, 0x70, 0x8c, 0x76, 0xa1, 0xc8, 0xa9, 0x6d, 0xd5,
	0xac, 0x7a, 0xc9, 0x2d, 0x72, 0x8a, 0x10, 0xfc, 0x27, 0xc8, 0x90, 0xd9, 0xc5, 0x9a, 0x55, 0xdf,
	0x76, 0xe3, 0xdf, 0xa8, 0x02, 0x1b, 0xfd, 0x50, 0x46, 0x81, 0x5d, 0x8a, 0x93, 0x49, 0x80, 0x47,
	0x70, 0x70, 0xce, 0xc5, 0x45, 0x02, 0xc5, 0x89, 0xdf, 0x16, 0x4a, 0x73, 0x1d, 0x69, 0x2e, 0x85,
	0xcb, 0xbe, 0x45, 0x4c, 0x69, 0x74, 0x08, 0x77, 0x82, 0xa8, 0xe7, 0x73, 0xaf, 0xab, 0xe5, 0x05,
	0x13, 0x31, 0xcc, 0xb6, 0xfb, 0x7f, 0x92, 0xeb, 0x4c, 0x52, 0xe8, 0x18, 0x2a, 0x31, 0xb9, 0x2e,
	0xbf, 0x2e, 0xef, 0x72, 0x9a, 0xe2, 0xa3, 0xf8, 0x6c, 0xa6, 0x73, 0x9b, 0xe2, 0x33, 0xa8, 0xe5,
	0xe3, 0xaa, 0x40, 0x0a, 0xc5, 0x90, 0x0d, 0x65, 0x15, 0x79, 0x1e, 0x53, 0x2a, 0xc6, 0xdc, 0x72,
	0xff, 0x86, 0xf8, 0x0c, 0x0e, 0x3f, 0x06, 0x94, 0x68, 0xb6, 0x8a, 0xf7, 0x3e, 0x94, 0xb9, 0x66,
	0xc3, 0xee, 0x74, 0x32, 0x9b, 0x93, 0xb0, 0x4d, 0xf1, 0x73, 0xc0, 0xab, 0xaa, 0x8d, 0xe8, 0xa7,
	0xf0, 0x20, 0x53, 0xdf, 0xf2, 0x3c, 0x19, 0x09, 0xad, 0x8c, 0xd0, 0xcf, 0xe0, 0x20, 0xb7, 0x74,
	0x9d, 0xaf, 0x76, 0xd9, 0x50, 0x8e, 0x6e, 0xfd, 0xd5, 0xab, 0xaa, 0x8d, 0xe8, 0x03, 0x78, 0xd4,
	0xa2, 0xf4, 0x1d, 0x57, 0x5a, 0x86, 0xdc, 0x23, 0xfe, 0xb4, 0x4d, 0x27, 0x24, 0x42, 0x11, 0x6f,
	0xd2, 0xc6, 0x38, 0x00, 0x84, 0x61, 0x27, 0xdd, 0x94, 0xf4, 0xb8, 0x98, 0x6e, 0x53, 0xbc, 0x22,
	0x09, 0xd3, 0x4f, 0x70, 0xb4, 0x0e, 0x52, 0xca, 0xb8, 0x0e, 0x7b, 0x82, 0x5d, 0xce, 0x1e, 0xa5,
	0x90, 0xd9, 0x34, 0xfe, 0x02, 0x07, 0x2d, 0x4a, 0xff, 0x1d, 0xef, 0x73, 0xa8, 0xe5, 0xf7, 0xbf,
	0x31, 0xdb, 0x1f, 0xd6, 0xc2, 0x1f, 0xb6, 0x8c, 0xf1, 0x43, 0xd8, 0xd3, 0xd7, 0xe9, 0x2e, 0xa7,
	0x93, 0x86, 0xa5, 0x7a, 0xc9, 0xdd, 0x9d, 0x49, 0xb7, 0xa9, 0x42, 0x27, 0x70, 0x2f, 0xf9, 0x82,
	0xec, 0xf5, 0x62, 0xad, 0x54, 0xdf, 0x76, 0xef, 0xc6, 0x87, 0x9d, 0xb9, 0x1a, 0x5c, 0x86, 0x8d,
	0xd7, 0xc3, 0x40, 0x8f, 0x4f, 0x7e, 0x97, 0xa1, 0xf2, 0x7e, 0xd6, 0x93, 0x3e, 0x24, 0xbe, 0x85,
	0xae, 0xc0, 0xce, 0xd3, 0x31, 0x72, 0x9c, 0x39, 0xc7, 0x72, 0x0c, 0x46, 0x53, 0x6d, 0xae, 0x7d,
	0x3f, 0x19, 0x26, 0x2e, 0xa0, 0x9f, 0x16, 0x54, 0xf3, 0xb5, 0x8c, 0x8e, 0x33, 0x1d, 0x8d, 0xa6,
	0x51, 0x7d, 0x7c, 0x83, 0x8a, 0x29, 0x8b, 0xef, 0xb0, 0x9f, 0xa3, 0x6a, 0xd4, 0x58, 0xdd, 0x2f,
	0x63, 0x1c, 0x55, 0x67, 0xdd, 0xeb, 0x73, 0x13, 0xc8, 0xd7, 0xf5, 0xc2, 0x04, 0x8c, 0x06, 0xb2,
	0x30, 0x01, 0xb3, 0x69, 0xe0, 0x02, 0xfa, 0x65, 0x01, 0x36, 0x6b, 0x16, 0x3d, 0xcd, 0xf4, 0x5e,
	0xdb, 0x50, 0xaa, 0xa7, 0xb7, 0xa8, 0x9c, 0xb2, 0xbb, 0x02, 0x3b, 0x4f, 0x98, 0x0b, 0x4b, 0x6a,
	0x70, 0x88, 0x85, 0x25, 0x35, 0x29, 0x1e, 0x17, 0xd0, 0x00, 0xee, 0xaf, 0x10, 0x32, 0x32, 0x0c,
	0x7c, 0x19, 0x89, 0x4a, 0xa6, 0x24, 0x16, 0x29, 0x2e, 0xbc, 0x68, 0x7f, 0x7e, 0xdb, 0xe7, 0x7a,
	0x10, 0xf5, 0x1c, 0x4f, 0x0e, 0x9b, 0x82, 0x31, 0xdf, 0x1b, 0xc8, 0x88, 0x0e, 0x48, 0x38, 0x6e,
	0xf6, 0x22, 0xda, 0x67, 0xfa, 0x92, 0xf8, 0x3e, 0xd3, 0x0d, 0x12, 0xf0, 0xc6, 0xe4, 0xe9, 0xc1,
	0xc2, 0xe6, 0xf2, 0x17, 0x48, 0x6f, 0x33, 0x7e, 0x74, 0x3c, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x78, 0xa7, 0xd1, 0x14, 0xa2, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaidFinancesServiceClient is the client API for PlaidFinancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaidFinancesServiceClient interface {
	LinkFinancialInstitution(ctx context.Context, in *LinkFinancialInstitutionRequest, opts ...grpc.CallOption) (*LinkFinancialInstitutionResponse, error)
	UpdateFinancialInstitution(ctx context.Context, in *UpdateFinancialInstitutionRequest, opts ...grpc.CallOption) (*UpdateFinancialInstitutionResponse, error)
	UpdateFinancialAccounts(ctx context.Context, in *UpdateFinancialAccountsRequest, opts ...grpc.CallOption) (*UpdateFinancialAccountsResponse, error)
	RemoveFinancialInstitution(ctx context.Context, in *RemoveFinancialInstitutionRequest, opts ...grpc.CallOption) (*RemoveFinancialInstitutionResponse, error)
	AddHistoricalFinancialTransactions(ctx context.Context, in *AddHistoricalFinancialTransactionsRequest, opts ...grpc.CallOption) (*AddHistoricalFinancialTransactionsResponse, error)
	AddFinancialTransactions(ctx context.Context, in *AddFinancialTransactionsRequest, opts ...grpc.CallOption) (*AddFinancialTransactionsResponse, error)
	RemoveFinancialTransactions(ctx context.Context, in *RemoveFinancialTransactionsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type plaidFinancesServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaidFinancesServiceClient(cc *grpc.ClientConn) PlaidFinancesServiceClient {
	return &plaidFinancesServiceClient{cc}
}

func (c *plaidFinancesServiceClient) LinkFinancialInstitution(ctx context.Context, in *LinkFinancialInstitutionRequest, opts ...grpc.CallOption) (*LinkFinancialInstitutionResponse, error) {
	out := new(LinkFinancialInstitutionResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/LinkFinancialInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) UpdateFinancialInstitution(ctx context.Context, in *UpdateFinancialInstitutionRequest, opts ...grpc.CallOption) (*UpdateFinancialInstitutionResponse, error) {
	out := new(UpdateFinancialInstitutionResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/UpdateFinancialInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) UpdateFinancialAccounts(ctx context.Context, in *UpdateFinancialAccountsRequest, opts ...grpc.CallOption) (*UpdateFinancialAccountsResponse, error) {
	out := new(UpdateFinancialAccountsResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/UpdateFinancialAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) RemoveFinancialInstitution(ctx context.Context, in *RemoveFinancialInstitutionRequest, opts ...grpc.CallOption) (*RemoveFinancialInstitutionResponse, error) {
	out := new(RemoveFinancialInstitutionResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/RemoveFinancialInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) AddHistoricalFinancialTransactions(ctx context.Context, in *AddHistoricalFinancialTransactionsRequest, opts ...grpc.CallOption) (*AddHistoricalFinancialTransactionsResponse, error) {
	out := new(AddHistoricalFinancialTransactionsResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/AddHistoricalFinancialTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) AddFinancialTransactions(ctx context.Context, in *AddFinancialTransactionsRequest, opts ...grpc.CallOption) (*AddFinancialTransactionsResponse, error) {
	out := new(AddFinancialTransactionsResponse)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/AddFinancialTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plaidFinancesServiceClient) RemoveFinancialTransactions(ctx context.Context, in *RemoveFinancialTransactionsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plaidfinances.PlaidFinancesService/RemoveFinancialTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaidFinancesServiceServer is the server API for PlaidFinancesService service.
type PlaidFinancesServiceServer interface {
	LinkFinancialInstitution(context.Context, *LinkFinancialInstitutionRequest) (*LinkFinancialInstitutionResponse, error)
	UpdateFinancialInstitution(context.Context, *UpdateFinancialInstitutionRequest) (*UpdateFinancialInstitutionResponse, error)
	UpdateFinancialAccounts(context.Context, *UpdateFinancialAccountsRequest) (*UpdateFinancialAccountsResponse, error)
	RemoveFinancialInstitution(context.Context, *RemoveFinancialInstitutionRequest) (*RemoveFinancialInstitutionResponse, error)
	AddHistoricalFinancialTransactions(context.Context, *AddHistoricalFinancialTransactionsRequest) (*AddHistoricalFinancialTransactionsResponse, error)
	AddFinancialTransactions(context.Context, *AddFinancialTransactionsRequest) (*AddFinancialTransactionsResponse, error)
	RemoveFinancialTransactions(context.Context, *RemoveFinancialTransactionsRequest) (*Empty, error)
}

// UnimplementedPlaidFinancesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlaidFinancesServiceServer struct {
}

func (*UnimplementedPlaidFinancesServiceServer) LinkFinancialInstitution(ctx context.Context, req *LinkFinancialInstitutionRequest) (*LinkFinancialInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkFinancialInstitution not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) UpdateFinancialInstitution(ctx context.Context, req *UpdateFinancialInstitutionRequest) (*UpdateFinancialInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinancialInstitution not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) UpdateFinancialAccounts(ctx context.Context, req *UpdateFinancialAccountsRequest) (*UpdateFinancialAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinancialAccounts not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) RemoveFinancialInstitution(ctx context.Context, req *RemoveFinancialInstitutionRequest) (*RemoveFinancialInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFinancialInstitution not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) AddHistoricalFinancialTransactions(ctx context.Context, req *AddHistoricalFinancialTransactionsRequest) (*AddHistoricalFinancialTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistoricalFinancialTransactions not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) AddFinancialTransactions(ctx context.Context, req *AddFinancialTransactionsRequest) (*AddFinancialTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFinancialTransactions not implemented")
}
func (*UnimplementedPlaidFinancesServiceServer) RemoveFinancialTransactions(ctx context.Context, req *RemoveFinancialTransactionsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFinancialTransactions not implemented")
}

func RegisterPlaidFinancesServiceServer(s *grpc.Server, srv PlaidFinancesServiceServer) {
	s.RegisterService(&_PlaidFinancesService_serviceDesc, srv)
}

func _PlaidFinancesService_LinkFinancialInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkFinancialInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).LinkFinancialInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/LinkFinancialInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).LinkFinancialInstitution(ctx, req.(*LinkFinancialInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_UpdateFinancialInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinancialInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).UpdateFinancialInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/UpdateFinancialInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).UpdateFinancialInstitution(ctx, req.(*UpdateFinancialInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_UpdateFinancialAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinancialAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).UpdateFinancialAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/UpdateFinancialAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).UpdateFinancialAccounts(ctx, req.(*UpdateFinancialAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_RemoveFinancialInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFinancialInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).RemoveFinancialInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/RemoveFinancialInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).RemoveFinancialInstitution(ctx, req.(*RemoveFinancialInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_AddHistoricalFinancialTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHistoricalFinancialTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).AddHistoricalFinancialTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/AddHistoricalFinancialTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).AddHistoricalFinancialTransactions(ctx, req.(*AddHistoricalFinancialTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_AddFinancialTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFinancialTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).AddFinancialTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/AddFinancialTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).AddFinancialTransactions(ctx, req.(*AddFinancialTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaidFinancesService_RemoveFinancialTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFinancialTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaidFinancesServiceServer).RemoveFinancialTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plaidfinances.PlaidFinancesService/RemoveFinancialTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaidFinancesServiceServer).RemoveFinancialTransactions(ctx, req.(*RemoveFinancialTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaidFinancesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plaidfinances.PlaidFinancesService",
	HandlerType: (*PlaidFinancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LinkFinancialInstitution",
			Handler:    _PlaidFinancesService_LinkFinancialInstitution_Handler,
		},
		{
			MethodName: "UpdateFinancialInstitution",
			Handler:    _PlaidFinancesService_UpdateFinancialInstitution_Handler,
		},
		{
			MethodName: "UpdateFinancialAccounts",
			Handler:    _PlaidFinancesService_UpdateFinancialAccounts_Handler,
		},
		{
			MethodName: "RemoveFinancialInstitution",
			Handler:    _PlaidFinancesService_RemoveFinancialInstitution_Handler,
		},
		{
			MethodName: "AddHistoricalFinancialTransactions",
			Handler:    _PlaidFinancesService_AddHistoricalFinancialTransactions_Handler,
		},
		{
			MethodName: "AddFinancialTransactions",
			Handler:    _PlaidFinancesService_AddFinancialTransactions_Handler,
		},
		{
			MethodName: "RemoveFinancialTransactions",
			Handler:    _PlaidFinancesService_RemoveFinancialTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/plaidfinances/plaidFinances.proto",
}
