BEGIN;

DROP TABLE IF EXISTS monthly_account_snapshots CASCADE;

DROP TABLE IF EXISTS daily_account_snapshots CASCADE;

DROP TABLE IF EXISTS transactions CASCADE;

DROP TABLE IF EXISTS category_mapping CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS plaid_categories CASCADE;

DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS items CASCADE;

DROP TABLE IF EXISTS users CASCADE;

COMMIT;