// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/dataprocessing/dataProcessing.proto

package dataprocessing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountDailySnapshot struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	CashOut              float64  `protobuf:"fixed64,5,opt,name=cash_out,json=cashOut,proto3" json:"cash_out,omitempty"`
	CashIn               float64  `protobuf:"fixed64,6,opt,name=cash_in,json=cashIn,proto3" json:"cash_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDailySnapshot) Reset()         { *m = AccountDailySnapshot{} }
func (m *AccountDailySnapshot) String() string { return proto.CompactTextString(m) }
func (*AccountDailySnapshot) ProtoMessage()    {}
func (*AccountDailySnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{0}
}

func (m *AccountDailySnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDailySnapshot.Unmarshal(m, b)
}
func (m *AccountDailySnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDailySnapshot.Marshal(b, m, deterministic)
}
func (m *AccountDailySnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDailySnapshot.Merge(m, src)
}
func (m *AccountDailySnapshot) XXX_Size() int {
	return xxx_messageInfo_AccountDailySnapshot.Size(m)
}
func (m *AccountDailySnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDailySnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDailySnapshot proto.InternalMessageInfo

func (m *AccountDailySnapshot) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AccountDailySnapshot) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountDailySnapshot) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *AccountDailySnapshot) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AccountDailySnapshot) GetCashOut() float64 {
	if m != nil {
		return m.CashOut
	}
	return 0
}

func (m *AccountDailySnapshot) GetCashIn() float64 {
	if m != nil {
		return m.CashIn
	}
	return 0
}

type GetAccountDailySnapshotsRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDailySnapshotsRequest) Reset()         { *m = GetAccountDailySnapshotsRequest{} }
func (m *GetAccountDailySnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountDailySnapshotsRequest) ProtoMessage()    {}
func (*GetAccountDailySnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{1}
}

func (m *GetAccountDailySnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Unmarshal(m, b)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDailySnapshotsRequest.Merge(m, src)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Size(m)
}
func (m *GetAccountDailySnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDailySnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDailySnapshotsRequest proto.InternalMessageInfo

func (m *GetAccountDailySnapshotsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetAccountDailySnapshotsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetAccountDailySnapshotsRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetAccountDailySnapshotsResponse struct {
	AccountDailySnapshots []*AccountDailySnapshot `protobuf:"bytes,1,rep,name=account_daily_snapshots,json=accountDailySnapshots,proto3" json:"account_daily_snapshots,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *GetAccountDailySnapshotsResponse) Reset()         { *m = GetAccountDailySnapshotsResponse{} }
func (m *GetAccountDailySnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountDailySnapshotsResponse) ProtoMessage()    {}
func (*GetAccountDailySnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{2}
}

func (m *GetAccountDailySnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Unmarshal(m, b)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDailySnapshotsResponse.Merge(m, src)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Size(m)
}
func (m *GetAccountDailySnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDailySnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDailySnapshotsResponse proto.InternalMessageInfo

func (m *GetAccountDailySnapshotsResponse) GetAccountDailySnapshots() []*AccountDailySnapshot {
	if m != nil {
		return m.AccountDailySnapshots
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccountDailySnapshot)(nil), "dataprocessing.AccountDailySnapshot")
	proto.RegisterType((*GetAccountDailySnapshotsRequest)(nil), "dataprocessing.GetAccountDailySnapshotsRequest")
	proto.RegisterType((*GetAccountDailySnapshotsResponse)(nil), "dataprocessing.GetAccountDailySnapshotsResponse")
	proto.RegisterType((*Empty)(nil), "dataprocessing.Empty")
}

func init() {
	proto.RegisterFile("services/dataprocessing/dataProcessing.proto", fileDescriptor_0a5d0ea3f8dbe2a8)
}

var fileDescriptor_0a5d0ea3f8dbe2a8 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x18, 0xc4, 0x4d, 0x9b, 0x52, 0x23, 0x71, 0xb0, 0xa8, 0x6a, 0x90, 0x10, 0x51, 0xc4, 0x21, 0x07,
	0x9a, 0xa0, 0xf2, 0x04, 0xa0, 0x22, 0x08, 0x17, 0x50, 0x7a, 0x43, 0x48, 0x95, 0x63, 0x7f, 0x6a,
	0x2c, 0xa5, 0x76, 0x88, 0x6d, 0x50, 0x4f, 0xf0, 0x18, 0xfb, 0x18, 0xfb, 0x88, 0xab, 0x38, 0xdb,
	0x55, 0x5b, 0xb5, 0xbb, 0x7b, 0xcb, 0x64, 0xbe, 0x9f, 0x99, 0xcf, 0x83, 0xdf, 0x19, 0x68, 0xff,
	0x48, 0x0e, 0x26, 0x13, 0xcc, 0xb2, 0xa6, 0xd5, 0x1c, 0x8c, 0x91, 0x6a, 0xe3, 0xe1, 0x8f, 0x3b,
	0x98, 0x36, 0xad, 0xb6, 0x9a, 0x3c, 0x3f, 0x2e, 0x8a, 0xaf, 0x11, 0x7e, 0xf1, 0x91, 0x73, 0xed,
	0x94, 0x5d, 0x32, 0x59, 0xef, 0x56, 0x8a, 0x35, 0xa6, 0xd2, 0x96, 0xcc, 0xf0, 0x58, 0x5a, 0xd8,
	0xae, 0xa5, 0xa0, 0x28, 0x42, 0x49, 0x50, 0x84, 0x1d, 0xcc, 0x05, 0x79, 0x8d, 0x31, 0xeb, 0x1b,
	0x3a, 0x6e, 0xe0, 0xb9, 0xc9, 0xed, 0x9f, 0x5c, 0x10, 0x82, 0x87, 0x82, 0x59, 0xa0, 0x41, 0x84,
	0x92, 0x49, 0xe1, 0xbf, 0x09, 0xc5, 0xe3, 0x92, 0xd5, 0x4c, 0x71, 0xa0, 0xc3, 0x08, 0x25, 0xa8,
	0xd8, 0x43, 0xf2, 0x12, 0x3f, 0xe5, 0xcc, 0x54, 0x6b, 0xed, 0x2c, 0x1d, 0xf5, 0x54, 0x87, 0xbf,
	0x3b, 0x2f, 0xc0, 0x53, 0x52, 0xd1, 0xd0, 0x33, 0x61, 0x07, 0x73, 0x15, 0xb7, 0xf8, 0xcd, 0x17,
	0xb0, 0xe7, 0x44, 0x9b, 0x02, 0x7e, 0x3b, 0x30, 0xbe, 0xd7, 0x19, 0x68, 0x0f, 0xc4, 0x77, 0x30,
	0x17, 0x87, 0xae, 0x06, 0xf7, 0xb8, 0x0a, 0x4e, 0x5c, 0xc5, 0xff, 0x11, 0x8e, 0x2e, 0x2f, 0x35,
	0x8d, 0x56, 0x06, 0xc8, 0x2f, 0x3c, 0xdb, 0xcf, 0x10, 0x5d, 0xc5, 0xda, 0xec, 0x4b, 0x28, 0x8a,
	0x82, 0xe4, 0xd9, 0xe2, 0x6d, 0x7a, 0x7c, 0xfd, 0xf4, 0xdc, 0xbc, 0x62, 0xca, 0xce, 0x6d, 0x89,
	0xc7, 0x78, 0xf4, 0x79, 0xdb, 0xd8, 0xdd, 0xe2, 0x0a, 0xe1, 0xe9, 0xf2, 0xe8, 0x6d, 0x57, 0x7d,
	0x02, 0xc8, 0x3f, 0x4c, 0x2f, 0x89, 0x24, 0xd9, 0xe9, 0xee, 0x07, 0x6e, 0xf8, 0xea, 0xfd, 0xe3,
	0x1b, 0x7a, 0xff, 0xf1, 0x93, 0x4f, 0xdf, 0x7e, 0x7e, 0xdd, 0x48, 0x5b, 0xb9, 0x32, 0xe5, 0x7a,
	0x9b, 0x29, 0x80, 0x9a, 0x57, 0xda, 0x89, 0x8a, 0xb5, 0xbb, 0xac, 0x74, 0x62, 0x03, 0xf6, 0x2f,
	0xab, 0x6b, 0xb0, 0x73, 0xd6, 0xc8, 0x79, 0x97, 0x5b, 0x68, 0xb3, 0x0b, 0xf1, 0x2d, 0x43, 0x1f,
	0xd8, 0x0f, 0x37, 0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0x8f, 0xc8, 0x50, 0xe0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataProcessingServiceClient is the client API for DataProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataProcessingServiceClient interface {
	GetAccountDailySnapshots(ctx context.Context, in *GetAccountDailySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountDailySnapshotsResponse, error)
}

type dataProcessingServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataProcessingServiceClient(cc *grpc.ClientConn) DataProcessingServiceClient {
	return &dataProcessingServiceClient{cc}
}

func (c *dataProcessingServiceClient) GetAccountDailySnapshots(ctx context.Context, in *GetAccountDailySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountDailySnapshotsResponse, error) {
	out := new(GetAccountDailySnapshotsResponse)
	err := c.cc.Invoke(ctx, "/dataprocessing.DataProcessingService/GetAccountDailySnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProcessingServiceServer is the server API for DataProcessingService service.
type DataProcessingServiceServer interface {
	GetAccountDailySnapshots(context.Context, *GetAccountDailySnapshotsRequest) (*GetAccountDailySnapshotsResponse, error)
}

// UnimplementedDataProcessingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataProcessingServiceServer struct {
}

func (*UnimplementedDataProcessingServiceServer) GetAccountDailySnapshots(ctx context.Context, req *GetAccountDailySnapshotsRequest) (*GetAccountDailySnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountDailySnapshots not implemented")
}

func RegisterDataProcessingServiceServer(s *grpc.Server, srv DataProcessingServiceServer) {
	s.RegisterService(&_DataProcessingService_serviceDesc, srv)
}

func _DataProcessingService_GetAccountDailySnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDailySnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessingServiceServer).GetAccountDailySnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataprocessing.DataProcessingService/GetAccountDailySnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessingServiceServer).GetAccountDailySnapshots(ctx, req.(*GetAccountDailySnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataProcessingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataprocessing.DataProcessingService",
	HandlerType: (*DataProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountDailySnapshots",
			Handler:    _DataProcessingService_GetAccountDailySnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/dataprocessing/dataProcessing.proto",
}
