// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/shared/shared.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FinancialAccount struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PlaidAccountId       string   `protobuf:"bytes,4,opt,name=plaid_account_id,json=plaidAccountId,proto3" json:"plaid_account_id,omitempty"`
	CurrentBalance       float64  `protobuf:"fixed64,5,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	AccountName          string   `protobuf:"bytes,6,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OfficialName         string   `protobuf:"bytes,7,opt,name=official_name,json=officialName,proto3" json:"official_name,omitempty"`
	AccountType          string   `protobuf:"bytes,8,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountSubtype       string   `protobuf:"bytes,9,opt,name=account_subtype,json=accountSubtype,proto3" json:"account_subtype,omitempty"`
	AccountMask          string   `protobuf:"bytes,10,opt,name=account_mask,json=accountMask,proto3" json:"account_mask,omitempty"`
	Selected             bool     `protobuf:"varint,11,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinancialAccount) Reset()         { *m = FinancialAccount{} }
func (m *FinancialAccount) String() string { return proto.CompactTextString(m) }
func (*FinancialAccount) ProtoMessage()    {}
func (*FinancialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f9ef3b942022a, []int{0}
}

func (m *FinancialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinancialAccount.Unmarshal(m, b)
}
func (m *FinancialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinancialAccount.Marshal(b, m, deterministic)
}
func (m *FinancialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinancialAccount.Merge(m, src)
}
func (m *FinancialAccount) XXX_Size() int {
	return xxx_messageInfo_FinancialAccount.Size(m)
}
func (m *FinancialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_FinancialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_FinancialAccount proto.InternalMessageInfo

func (m *FinancialAccount) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FinancialAccount) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FinancialAccount) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *FinancialAccount) GetPlaidAccountId() string {
	if m != nil {
		return m.PlaidAccountId
	}
	return ""
}

func (m *FinancialAccount) GetCurrentBalance() float64 {
	if m != nil {
		return m.CurrentBalance
	}
	return 0
}

func (m *FinancialAccount) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *FinancialAccount) GetOfficialName() string {
	if m != nil {
		return m.OfficialName
	}
	return ""
}

func (m *FinancialAccount) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *FinancialAccount) GetAccountSubtype() string {
	if m != nil {
		return m.AccountSubtype
	}
	return ""
}

func (m *FinancialAccount) GetAccountMask() string {
	if m != nil {
		return m.AccountMask
	}
	return ""
}

func (m *FinancialAccount) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type FinancialInstitution struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstitutionName      string   `protobuf:"bytes,2,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	InstitutionColor     string   `protobuf:"bytes,3,opt,name=institution_color,json=institutionColor,proto3" json:"institution_color,omitempty"`
	InstitutionLogo      string   `protobuf:"bytes,4,opt,name=institution_logo,json=institutionLogo,proto3" json:"institution_logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinancialInstitution) Reset()         { *m = FinancialInstitution{} }
func (m *FinancialInstitution) String() string { return proto.CompactTextString(m) }
func (*FinancialInstitution) ProtoMessage()    {}
func (*FinancialInstitution) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f9ef3b942022a, []int{1}
}

func (m *FinancialInstitution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinancialInstitution.Unmarshal(m, b)
}
func (m *FinancialInstitution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinancialInstitution.Marshal(b, m, deterministic)
}
func (m *FinancialInstitution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinancialInstitution.Merge(m, src)
}
func (m *FinancialInstitution) XXX_Size() int {
	return xxx_messageInfo_FinancialInstitution.Size(m)
}
func (m *FinancialInstitution) XXX_DiscardUnknown() {
	xxx_messageInfo_FinancialInstitution.DiscardUnknown(m)
}

var xxx_messageInfo_FinancialInstitution proto.InternalMessageInfo

func (m *FinancialInstitution) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FinancialInstitution) GetInstitutionName() string {
	if m != nil {
		return m.InstitutionName
	}
	return ""
}

func (m *FinancialInstitution) GetInstitutionColor() string {
	if m != nil {
		return m.InstitutionColor
	}
	return ""
}

func (m *FinancialInstitution) GetInstitutionLogo() string {
	if m != nil {
		return m.InstitutionLogo
	}
	return ""
}

type Transaction struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CategoryId           int64    `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PlaidCategoryId      string   `protobuf:"bytes,6,opt,name=plaid_category_id,json=plaidCategoryId,proto3" json:"plaid_category_id,omitempty"`
	PlaidTransactionId   string   `protobuf:"bytes,7,opt,name=plaid_transaction_id,json=plaidTransactionId,proto3" json:"plaid_transaction_id,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Amount               float64  `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Date                 string   `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	Pending              bool     `protobuf:"varint,11,opt,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f9ef3b942022a, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Transaction) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Transaction) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Transaction) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Transaction) GetPlaidCategoryId() string {
	if m != nil {
		return m.PlaidCategoryId
	}
	return ""
}

func (m *Transaction) GetPlaidTransactionId() string {
	if m != nil {
		return m.PlaidTransactionId
	}
	return ""
}

func (m *Transaction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

func init() {
	proto.RegisterType((*FinancialAccount)(nil), "shared.FinancialAccount")
	proto.RegisterType((*FinancialInstitution)(nil), "shared.FinancialInstitution")
	proto.RegisterType((*Transaction)(nil), "shared.Transaction")
}

func init() { proto.RegisterFile("services/shared/shared.proto", fileDescriptor_a31f9ef3b942022a) }

var fileDescriptor_a31f9ef3b942022a = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xd2, 0xdd, 0x7e, 0x4c, 0x97, 0xb6, 0x6b, 0xad, 0x20, 0x42, 0x20, 0x4a, 0x39, 0x50,
	0x40, 0xda, 0x22, 0x71, 0x43, 0x5c, 0xd8, 0x95, 0x90, 0x22, 0x01, 0x87, 0xb0, 0x27, 0x2e, 0x95,
	0x6b, 0xcf, 0xa6, 0xd6, 0x26, 0x76, 0x64, 0x3b, 0x48, 0xfd, 0x49, 0xfc, 0x12, 0xfe, 0x13, 0x27,
	0x64, 0x3b, 0x69, 0xb3, 0x85, 0x0b, 0xa7, 0x64, 0xde, 0x7b, 0x7a, 0x9e, 0xf1, 0x3c, 0xc3, 0x13,
	0x83, 0xfa, 0x87, 0x60, 0x68, 0x56, 0x66, 0x4b, 0x35, 0xf2, 0xe6, 0x73, 0x59, 0x69, 0x65, 0x15,
	0xe9, 0x87, 0x6a, 0xf1, 0x3b, 0x86, 0xd9, 0x27, 0x21, 0xa9, 0x64, 0x82, 0x16, 0x1f, 0x19, 0x53,
	0xb5, 0xb4, 0x64, 0x02, 0xb1, 0xe0, 0x49, 0x34, 0x8f, 0x96, 0xbd, 0x2c, 0x16, 0x9c, 0x3c, 0x82,
	0x41, 0x6d, 0x50, 0xaf, 0x05, 0x4f, 0x62, 0x0f, 0xf6, 0x5d, 0x99, 0x7a, 0x42, 0x58, 0x2c, 0x1d,
	0xd1, 0x0b, 0x84, 0x2b, 0x53, 0x4e, 0x96, 0x30, 0xab, 0x0a, 0x2a, 0xf8, 0x9a, 0x06, 0x4b, 0xa7,
	0x38, 0x99, 0x47, 0xcb, 0x51, 0x36, 0xf1, 0x78, 0x73, 0x52, 0xca, 0xc9, 0x4b, 0x98, 0xb2, 0x5a,
	0x6b, 0x94, 0x76, 0xbd, 0xa1, 0x05, 0x95, 0x0c, 0x93, 0xd3, 0x79, 0xb4, 0x8c, 0xb2, 0x49, 0x03,
	0x5f, 0x05, 0x94, 0x3c, 0x87, 0xb3, 0xd6, 0x4c, 0xd2, 0x12, 0x93, 0xbe, 0xb7, 0x1b, 0x37, 0xd8,
	0x57, 0x5a, 0x22, 0x79, 0x01, 0x0f, 0xd4, 0xed, 0xad, 0x70, 0xa3, 0x04, 0xcd, 0xc0, 0x6b, 0xce,
	0x5a, 0xd0, 0x8b, 0x3a, 0x3e, 0x76, 0x57, 0x61, 0x32, 0xbc, 0xe7, 0x73, 0xb3, 0xab, 0xd0, 0xf5,
	0xd4, 0x4a, 0x4c, 0xbd, 0xf1, 0xaa, 0x51, 0x68, 0xbe, 0x81, 0xbf, 0x05, 0xb4, 0xeb, 0x55, 0x52,
	0x73, 0x97, 0xc0, 0x3d, 0xaf, 0x2f, 0xd4, 0xdc, 0x91, 0xc7, 0x30, 0x34, 0x58, 0x20, 0xb3, 0xc8,
	0x93, 0xf1, 0x3c, 0x5a, 0x0e, 0xb3, 0x7d, 0xbd, 0xf8, 0x19, 0xc1, 0xc5, 0xfe, 0xf2, 0x53, 0x69,
	0xac, 0xb0, 0xb5, 0x15, 0x4a, 0xfe, 0xb5, 0x80, 0x57, 0x30, 0x13, 0x07, 0x3a, 0xcc, 0x16, 0xfb,
	0xb3, 0xa6, 0x1d, 0xdc, 0x8f, 0xf7, 0x06, 0xce, 0xbb, 0x52, 0xa6, 0x0a, 0xa5, 0xfd, 0x72, 0x46,
	0x59, 0xd7, 0xe3, 0xda, 0xe1, 0xc7, 0xbe, 0x85, 0xca, 0x55, 0xb3, 0xa6, 0xae, 0xef, 0x67, 0x95,
	0xab, 0xc5, 0xaf, 0x18, 0xc6, 0x37, 0x9a, 0x4a, 0x43, 0xd9, 0x3f, 0x5b, 0xfc, 0xff, 0x8c, 0x3c,
	0x05, 0x38, 0x4a, 0x47, 0x2f, 0x1b, 0xd1, 0x7d, 0x30, 0x9e, 0xc1, 0x98, 0x51, 0x8b, 0xb9, 0xd2,
	0x3b, 0xc7, 0x9f, 0x7a, 0x1e, 0x5a, 0x28, 0xe5, 0xe4, 0x35, 0x9c, 0x87, 0x8c, 0x75, 0x65, 0x21,
	0x15, 0x53, 0x4f, 0x5c, 0x1f, 0xb4, 0x6f, 0xe1, 0x22, 0x68, 0xed, 0x61, 0x04, 0x27, 0x0f, 0x01,
	0x21, 0x9e, 0xeb, 0x4c, 0x97, 0x72, 0x42, 0xe0, 0xc4, 0x5f, 0x73, 0x88, 0x87, 0xff, 0x27, 0x0f,
	0xa1, 0x4f, 0x4b, 0xd7, 0x9e, 0x8f, 0x43, 0x94, 0x35, 0x95, 0xd3, 0x72, 0x6a, 0xb1, 0x59, 0xbf,
	0xff, 0x27, 0x09, 0x0c, 0x2a, 0x94, 0x5c, 0xc8, 0xbc, 0x59, 0x7b, 0x5b, 0x5e, 0x7d, 0xf8, 0xfe,
	0x3e, 0x17, 0x76, 0x5b, 0x6f, 0x2e, 0x99, 0x2a, 0x57, 0x12, 0xb1, 0x60, 0x5b, 0x55, 0xf3, 0x2d,
	0xd5, 0xbb, 0xd5, 0xa6, 0xe6, 0x39, 0xda, 0x92, 0x4a, 0x9a, 0xa3, 0xce, 0x75, 0xc5, 0x56, 0x47,
	0xaf, 0x78, 0xd3, 0xf7, 0xef, 0xf7, 0xdd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xc4, 0x4b,
	0xf9, 0xdf, 0x03, 0x00, 0x00,
}
